name: Sedstart OODO Crictical Workflow

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_QA_OODO }}
          project_id: 1022
          test_id: 8881
          profile_id: 1931
          browser: chromium
          headless: true
